### ISSUE TITLE
Typo in fileoperations

### ISSUE THREAD

**Issue by jbrgfx** [aadityamp01/Assembly-Programming#1]
Fileoperations NASM/fileop.asm

Print command for open file contains a typo:
line 152 reads: cmn 1,1,buf,abuf_len ;printing file content on screen

It works when the **buf_len** is called as in:
cmn 1,1,buf,buf_len ;printing file content on screen

**Comment by aadityamp01** [comment]
Hey @jbrgfx thanks for raising this issue. 🙂
It's fixed!
